on:
  push:
    branches: ["*"]

jobs:
  tests:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install
        run: |
          npm install

      - name: Browsers
        run: npx cypress info

      - name: Edge
        run: npm run test:headless edge

      # - name: Electron
      #   run: npm run test:headless electron
