on:
  push:
    branches: ["*"]

jobs:
  tests:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node_modules-

      - name: Install
        run: npm install

      - name: Edage
        run: npm run test:headless edge

  firefox:
    run-on: ubuntu-latest
    services:
      chrome:
        image: cypress/browsers:node14.16.0-chrome89-ff86
    needs: setup-node_modules
    steps:
      - name: Load node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install
        run: npm install

      - name: Chrome
        run: npm run test:headless chrome

      # - name: Electron
      #   run: npm run test:headless electron
