on:
  push:
    branches: ["*"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci

      - name: Run Component tests 🧪
        uses: cypress-io/github-action@v2
        with:
          # we have already installed everything
          install: false
          # to run component tests we need to use "cypress run-ct"
          command: yarn cypress run-ct
