on:
  push:
    branches: ["*"]

jobs:
  tests:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install
        run: |
          npm install

      - name: Edge
        run: npm run test:edge

      # - name: Chrome
      #   run: npm run test:headless chrome

      # - name: Electron
      #   run: npm run test:headless electron

  tests2:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install
        run: |
          npm install

      - name: Chrome
        run: npm run test:chrome

      # - name: Electron
      #   run: npm run test:headless electron
