on:
  push:
    branches: ["*"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Run Component tests
        run: npm run test:headless
