on:
  push:
    branches: ["*"]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install
        run: npm install

      - name: Chrome
        run: npm run test:headless chrome

      - name: Firefox
        run: npm run test:headless firefox

      - name: Edge
        run: npm run test:headless edge

      - name: Electron
        run: npm run test:headless electron
