name: Run linters and specs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job name
  suite:
    # OS of the runner
    runs-on: ubuntu-latest

    steps:
      - name: Install
        run: npm install

      - name: Checkout
        uses: cypress-io/github-action@v2
        run: npm run test:headless
        
